metanorma/packed-mn

.github/workflows/compile_linux.yml
.github/workflows/compile_osx.yml
.github/workflows/release.yml
Gemfile

- #20 
`release.yml` workflow will be triggered by https://github.com/metanorma/metanorma-cli/pull/137
`Gemfile` will check for `GITHUB_REF` env variable to understand is this release or not

#20 listen for metanorma-cli release

---

.github/workflows/compile_linux.yml
.github/workflows/compile_osx.yml
Gemfile
Gemfile.lock
Makefile
bin/build.sh
bin/metanorma

#6 Implement workaround for ffi_lib loading

---

bin/build.sh

- Potential fix for #24
@ronaldtse @w00lf if you have an idea where to test this please let me know
Based on https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources GHA provide only OSX 10.5

#24 Fix 'Symbol not found: ____chkstk_darwin' runtime error

---

.github/workflows/build.yml

#30 add metanorma setup

---

bin/metanorma

#49 Fix for external tools including sassc, mn2pdf.jar and mn2sts.jar

---

bin/metanorma

- #62 
P.S. I have a problem with building it locally again(, for some reason compilation just hung on `compiling prelude.c`
I will do final tests on binary form CI

#62 fix PDF generation command

---

bin/build.sh

- related to https://github.com/metanorma/metanorma-snap/pull/10

Perform strip to remove any unnecesarry data/code from result binary

---

.github/workflows/windows.yml
Makefile.win

#74 test help after compilation

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
Gemfile
Makefile
Makefile.win
bin/metanorma

#100 #116 Fix missing libarchive and local Gemfile

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

#122 
- `No` Breaking changes (list related PRs)
- `No` Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
- `No` External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
- `No` Gem with native library introduced

#122 add sha265.txt alongside with binaries

---

bin/metanorma

This is intended for test purposes, as discussed with @maxirmx

WIP: Test both paths

---

.github/workflows/linux.yml
.github/workflows/macos.yml
bin/metanorma

Test without Gemfile in cwd

---

.github/workflows/linux.yml
.github/workflows/macos.yml
Makefile
bin/metanorma

- This PR addresses  https://github.com/metanorma/eccma-iso-scor-vocab/issues/1  
- Additional redundant call to bundle is removed from packaging step

Fixed an issue with Gemfile in cwd

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

Attempt to clean up GHA tests

---

Makefile
bin/metanorma

Remove SSL hack

---

.github/workflows/linux.yml
.github/workflows/macos.yml
Makefile

tebako 0.3.5 / glog 0.6.0

---

.github/workflows/linux.yml
.github/workflows/macos.yml

Save source filesystem as GHA artifact for verification

---

.github/workflows/linux.yml

- metanorma/metanorma-snap#22
- https://github.com/metanorma/packed-mn/pull/56#issuecomment-1126908378

metanorma/metanorma-snap#22 build libsaasc with static stdlibc++

---

Gemfile
bin/metanorma

(due to introduction of  seven-zip gem aka https://github.com/fontist/seven_zip_ruby)

Replace seven_zip_ruby reference with seven-zip

---

.github/workflows/windows.yml
Makefile.win
bin/metanorma

#175 downgrade bundler to 2.3.20

---

.github/workflows/windows.yml

- https://github.com/metanorma/packed-mn/actions/runs/3232441737/jobs/5293175623

Workaround for bundle install issue

---

.github/workflows/alpine.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
ubuntu.env

Related issues:
- https://github.com/metanorma/emf2svg-ruby/issues/37

Upgrade build runner from 18.04 to 20.04

---

Makefile.win

libffi version bump

---

Makefile.win
ocra/patch/rouge-win-path.patch

#185 fix OCRA rouge-4.0.1/lib/rouge/lexers/abap.rb (LoadError)

---

.github/workflows/macos.yml

#192 install libgflags

---

.github/workflows/alpine.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
bin/metanorma

- metanorma/metanorma-iso#944
- https://github.com/metanorma/iso-19135/issues/33

metanorma/metanorma-iso#944 update MnConvert.convert signature

---

.cirrus.yml

Fixed cirrus workflows

---

.github/workflows/alpine.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

fix: install xml2rfc for test pass

---

.cirrus.star
.cirrus.yml
.github/workflows/alpine.yml
.github/workflows/macos-arm64.yml
.github/workflows/macos-x86_64.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
README.adoc
common.env

* Moved packed-mn arm64 MacOS build from Cirrus CI to GHA
* Created metanorma-darwin-arm64 release artifact

Moved packed-mn arm64 MacOS build from Cirrus CI to GHA

---

.github/workflows/ubuntu.yml
Makefile

fix: forward compatability of Ubuntu version

---

.github/workflows/macos-x86_64.yml

chore: change  macos runner from macos-12 to macos-13

---

.github/workflows/macos-x86_64.yml

Update xcode to 15.2 for macos-x86_64

---

.github/workflows/alpine.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
Makefile
bin/metanorma
common.env

chore: patch plurimath issue and bump Ruby version to 3.4.2
